import {useEffect,useRef,useState} from 'react';
import {Link} from '@tanstack/react-router';
import {useSnapshot,useStore} from '../app/context';
import {opponentFor,signedDelta} from '../domain/rating.js';
import {STORAGE_KEY} from '../services/store';
import {ItemArt} from '../shared/ui/Piece';
interface InstallEvent extends Event {prompt:()=>Promise<void>}
export const ProfileScreen=()=>{
 const {data}=useSnapshot(),store=useStore(),input=useRef<HTMLInputElement>(null);
 const [install,setInstall]=useState<InstallEvent|null>(null),[instructions,setInstructions]=useState(false);
 useEffect(()=>{const listener=(event:Event)=>{event.preventDefault();setInstall(event as InstallEvent);};window.addEventListener('beforeinstallprompt',listener);return()=>window.removeEventListener('beforeinstallprompt',listener);},[]);
 const download=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='chess-vault-preprod.json';a.click();URL.revokeObjectURL(url);};
 return <section id="profile"><h1>Профиль</h1><div className="profile-grid"><div className="profile-overview"><article className="panel rating-card"><p className="eyebrow">ВАШ ВНУТРЕННИЙ РЕЙТИНГ</p><div className="rating-heading"><strong>{data.rating.value}</strong><span>{signedDelta(data.rating.lastDelta)}</span></div><p>{data.rating.games<10?`Калибровка · ${data.rating.games}/10 партий`:'Калибровка завершена'}</p><progress max={10} value={Math.min(10,data.rating.games)} aria-label="Калибровка рейтинга"/><p>Следующий соперник: {opponentFor(data.rating.value)}</p><details><summary>Как работает адаптация?</summary><p>Победа повышает рейтинг, поражение и сдача снижают его. Первые десять партий быстрее уточняют оценку. Это внутренняя шкала прогресса, а не рейтинг FIDE.</p></details></article><div className="profile-stats"><article className="panel"><strong>{data.played}</strong><p>Партий</p></article><article className="panel"><strong>{data.opened}</strong><p>Сундуков</p></article></div><article className="panel"><h2>Выбранный набор</h2><div className="equipment-slots">{[...Object.values(data.equipped.pieces),data.equipped.board].map(id=><span className="preset-part" key={id}><ItemArt id={id}/></span>)}</div></article><button className="quiet" onClick={()=>{if(install)void install.prompt();else setInstructions(true);}}>Установить приложение</button>{instructions&&<p>На iPhone: Safari → «Поделиться» → «На экран Домой». В других браузерах используйте пункт установки приложения.</p>}<p><Link to="/faq" className="text-button">Вопросы и ответы</Link></p><article className="panel archive-panel"><h2>История партий</h2>{data.archive.length?data.archive.map(entry=><Link key={entry.id} className="archive-entry" to="/profile/history/$gameId" params={{gameId:entry.id}}><span><strong>{entry.result}</strong><small>{entry.finishedAt?new Date(entry.finishedAt).toLocaleString('ru-RU'):''} · {entry.playerColor==='w'?'Белые':'Чёрные'}</small></span><span>{entry.points} очк.<small>Рейтинг {entry.playerRating}{entry.ratingDelta!==null?` (${signedDelta(entry.ratingDelta)})`:''}</small></span></Link>):<p className="muted">Здесь появятся завершённые партии.</p>}</article><details className="panel"><summary>Тестовые сохранения</summary><p>Preprod хранит отдельный прогресс. Можно импортировать копию сохранения из файла или скачать текущий снимок.</p><button className="quiet" onClick={download}>Скачать сохранение</button><button className="quiet" onClick={()=>input.current?.click()}>Импортировать копию</button><input ref={input} type="file" accept="application/json,.json" hidden onChange={async event=>{const file=event.target.files?.[0];if(!file)return;try{const value:unknown=JSON.parse(await file.text());if(!value||typeof value!=='object'||!('version' in value)||!('game' in value))throw Error();store.importData(value);}catch{store.setError('Не удалось прочитать файл сохранения.');}event.target.value='';}}/><small>Ключ: {STORAGE_KEY}</small></details></div></div></section>;
};
