import test from 'node:test';
import assert from 'node:assert/strict';
import {Chess} from '../dist/chess.js';
import {rewardFor, chooseMove, DIFFICULTIES} from '../dist/engine.js';
import {animationMoves} from '../dist/board.js';
test('Незавершённая партия и быстрая сдача не дают награды',()=>{const game=new Chess();game.move('e4');assert.equal(rewardFor(game),0);assert.equal(rewardFor(game,true),0);});
test('Мат раньше десяти полуходов даёт награду проигравшему',()=>{const game=new Chess();['f3','e5','g4','Qh4#'].forEach(move=>game.move(move));assert.equal(rewardFor(game),25);});
test('Победа белых даёт 60 монет',()=>{const game=new Chess();['e4','e5','Bc4','Nc6','Qh5','Nf6','Qxf7#'].forEach(move=>game.move(move));assert.equal(rewardFor(game),60);});
test('Все уровни компьютера находят мат в один ход',()=>{for(const level of Object.keys(DIFFICULTIES)){const game=new Chess();['f3','e5','g4'].forEach(move=>game.move(move));game.move(chooseMove(game.fen(),level,()=>0));assert.equal(game.isCheckmate(),true,level);}});
test('Сложный уровень возвращает легальный ход в пределах бюджета',()=>{const game=new Chess();game.move('e4');const before=performance.now();const move=chooseMove(game.fen(),'hard',()=>0);assert.ok(game.move(move));assert.ok(performance.now()-before<4000);});
test('Компьютер не ходит после окончания партии',()=>{const game=new Chess('8/8/8/8/8/4k3/8/4K3 b - - 0 1');assert.equal(chooseMove(game.fen(),'hard'),null);});
test('Рокировка, взятие на проходе и превращение поддерживаются',()=>{const castle=new Chess('r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1');castle.move('O-O');assert.equal(castle.get('f1').type,'r');const ep=new Chess();['e4','a6','e5','d5','exd6'].forEach(move=>ep.move(move));assert.equal(ep.get('d5'),undefined);const promo=new Chess('7k/P7/8/8/8/8/8/7K w - - 0 1');promo.move({from:'a7',to:'a8',promotion:'n'});assert.equal(promo.get('a8').type,'n');});
test('Рокировка анимирует короля и ладью на обеих сторонах',()=>{assert.deepEqual(animationMoves({from:'e1',to:'g1',flags:'k'}),[{from:'e1',to:'g1'},{from:'h1',to:'f1'}]);assert.deepEqual(animationMoves({from:'e8',to:'c8',flags:'q'}),[{from:'e8',to:'c8'},{from:'a8',to:'d8'}]);});
test('PGN сохраняет историю для повтора позиции',()=>{const game=new Chess();['Nf3','Nf6','Ng1','Ng8','Nf3','Nf6','Ng1','Ng8'].forEach(move=>game.move(move));const restored=new Chess();restored.loadPgn(game.pgn());assert.equal(restored.isThreefoldRepetition(),true);});
