import test from 'node:test';
import assert from 'node:assert/strict';
import {createStore,STORAGE_KEY} from '../src/services/store.ts';
const storage=()=>{const values=new Map<string,string>();return {getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value);},removeItem:(key:string)=>{values.delete(key);},clear:()=>values.clear(),key:(index:number)=>[...values.keys()][index]??null,get length(){return values.size;}};};
test('Preprod не читает и не перезаписывает рабочую коллекцию',()=>{const db=storage();db.setItem('chess-vault-v3','production');const store=createStore();store.initialize(db);assert.equal(store.getSnapshot().data.coins,100);store.openChest();assert.equal(db.getItem('chess-vault-v3'),'production');assert.equal(store.getSnapshot().data.coins,0);assert.ok(db.getItem(STORAGE_KEY));});
test('Сдача сохраняет результат один раз и держит финальную доску до закрытия',()=>{const db=storage(),store=createStore();store.initialize(db);store.start();assert.equal(store.getSnapshot().data.game.engineProfile?.id,'stockfish19-v1');store.resign();const final=store.getSnapshot();assert.equal(final.data.archive.length,1);assert.ok(final.result);store.resign();assert.equal(store.getSnapshot().data.archive.length,1);store.dismissResult();assert.equal(store.getSnapshot().result,null);const next=createStore();next.initialize(db);assert.equal(next.getSnapshot().data.archive.length,1);assert.equal(next.getSnapshot().data.rating.games,1);assert.equal(next.getSnapshot().result,null);});
test('Активная партия блокирует операции коллекции и сундука',()=>{const store=createStore();store.initialize(storage());store.start();const data=store.getSnapshot().data;store.openChest();store.saveSet('blocked');store.craft('piece:sand:k');assert.equal(store.getSnapshot().data,data);});
test('Ошибка записи не применяет транзакцию и не теряет активную партию',()=>{const db=storage(),store=createStore();store.initialize(db);store.start();const before=store.getSnapshot().data;db.setItem=()=>{throw Error('quota');};store.resign();assert.equal(store.getSnapshot().data,before);assert.equal(store.getSnapshot().result,null);assert.ok(store.getSnapshot().error);});
test('Шахматные ходы сохраняются и возобновляются из PGN',()=>{const db=storage(),store=createStore();store.initialize(db);store.start();const bot=store.getSnapshot().data.game.playerColor==='b';assert.ok(store.play({from:'e2',to:'e4'},bot));const pgn=store.getSnapshot().data.game.pgn;const resumed=createStore();resumed.initialize(db);assert.equal(resumed.getSnapshot().data.game.pgn,pgn);assert.equal(resumed.getSnapshot().data.game.started,true);});
