/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChestsRouteImport } from './routes/chests'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CraftRouteImport } from './routes/craft'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProfileHistoryGameIdRouteImport } from './routes/profile_.history.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChestsRoute = ChestsRouteImport.update({
  id: '/chests',
  path: '/chests',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHistoryGameIdRoute = ProfileHistoryGameIdRouteImport.update({
  id: '/profile_/history/$gameId',
  path: '/profile/history/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chests': typeof ChestsRoute
  '/collection': typeof CollectionRoute
  '/craft': typeof CraftRoute
  '/faq': typeof FaqRoute
  '/profile': typeof ProfileRoute
  '/profile/history/$gameId': typeof ProfileHistoryGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chests': typeof ChestsRoute
  '/collection': typeof CollectionRoute
  '/craft': typeof CraftRoute
  '/faq': typeof FaqRoute
  '/profile': typeof ProfileRoute
  '/profile/history/$gameId': typeof ProfileHistoryGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chests': typeof ChestsRoute
  '/collection': typeof CollectionRoute
  '/craft': typeof CraftRoute
  '/faq': typeof FaqRoute
  '/profile': typeof ProfileRoute
  '/profile_/history/$gameId': typeof ProfileHistoryGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chests'
    | '/collection'
    | '/craft'
    | '/faq'
    | '/profile'
    | '/profile/history/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chests'
    | '/collection'
    | '/craft'
    | '/faq'
    | '/profile'
    | '/profile/history/$gameId'
  id:
    | '__root__'
    | '/'
    | '/chests'
    | '/collection'
    | '/craft'
    | '/faq'
    | '/profile'
    | '/profile_/history/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChestsRoute: typeof ChestsRoute
  CollectionRoute: typeof CollectionRoute
  CraftRoute: typeof CraftRoute
  FaqRoute: typeof FaqRoute
  ProfileRoute: typeof ProfileRoute
  ProfileHistoryGameIdRoute: typeof ProfileHistoryGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chests': {
      id: '/chests'
      path: '/chests'
      fullPath: '/chests'
      preLoaderRoute: typeof ChestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/history/$gameId': {
      id: '/profile_/history/$gameId'
      path: '/profile/history/$gameId'
      fullPath: '/profile/history/$gameId'
      preLoaderRoute: typeof ProfileHistoryGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChestsRoute: ChestsRoute,
  CollectionRoute: CollectionRoute,
  CraftRoute: CraftRoute,
  FaqRoute: FaqRoute,
  ProfileRoute: ProfileRoute,
  ProfileHistoryGameIdRoute: ProfileHistoryGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
